### ISSUE TITLE
Feature 1: User can view list view of activities

### ISSUE THREAD

**Issue by rosemary-liang** [rosemary-liu/toddletots#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

- User can view all activities on home page and select an activity to drill down for further details.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

- User can see all activities, which will contain a preview of each activity containing title, distance from current location, and photo carousel. 
- Photo carousel does not have a timer, user can use arrow buttons to view additional photos.
- Activities are displayed from shortest distance to farthest distance.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Home](https://user-images.githubusercontent.com/95596680/162845735-16d9f84e-14f5-41f2-a1f5-7de04899388b.png)

![Home (1)](https://user-images.githubusercontent.com/95596680/162845741-2da954d3-fc0c-4ae8-8a69-b7cc71359973.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### 🐘 Database

- [x] Update `schema.sql` using DbDesigner export
- [x] Update `data.sql` to have:
   - [x] complete data for 3 examples (Victory Park, Adventure Playground, Parasol Park)
   - [x] dummy userId=1

### ☁️ Server

- [x] Update `server/index.js` to handle fetch requests to get all activity information needed to populate all individual activities
   - [x] Add db.js
   - [x] Write sql query to GET all data needed
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client

- [x] Set up hash routing
- [x] Update `client/lib/index.js` to export parseRoute
- [x] Create a component to display the App
- [x] Create component to display header and hamburger menu
- [x] Create component for search bar. Add button for submit.
   - [x] Ensure submit button works
- [x] Create component to contain activities
- [x] Create component to display each activity
     - [x] Create component to contain photo carousel
- [x] Create component for footer ribbon
- [x] Activities load in order of distance from current location
- [x] Activities load in order of distance from zip code entered in search bar
   - [x] Edit title when searching by zip vs current location
   - [x] Error validation for invalid zip code

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
