### ISSUE TITLE
Feature 12: User can sign up

### ISSUE THREAD

**Issue by rosemary-liang** [rosemary-liu/toddletots#12]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can sign up and create a username and password.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User can sign up for an account by navigating through the hamburger menu and clicking "Sign Up" in bottom left corner of the login page. 

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/95596680/167318269-c095128f-2b05-4738-b6f5-84f8e00e50f2.png)
<img width="1319" alt="image" src="https://user-images.githubusercontent.com/95596680/167318274-62c7525c-7e46-43fe-a6a3-546b90349153.png">

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### 🐘 Database

- [x] Update `schema.sql` to remove all fields except username and hashedPassword
- [x] Update `data.sql` to to remove all fields except username and hashedPassword

### ☁️ Server

- [x] Update `server/index.js` to process POST requests to the users table at the sign-up endpoint
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client

- [x] Create Auth page component to handle sign in and sign up
   - [x] Update hash routing
- [x] Update HamburgerMenu component to go to Auth page on click. 

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
