### ISSUE TITLE
Feature 13: User can sign in 

### ISSUE THREAD

**Issue by rosemary-liang** [rosemary-liu/toddletots#13]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can sign in.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User can sign up for an account by navigating through the hamburger menu.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/95596680/167318269-c095128f-2b05-4738-b6f5-84f8e00e50f2.png)
<img width="1319" alt="image" src="https://user-images.githubusercontent.com/95596680/167318274-62c7525c-7e46-43fe-a6a3-546b90349153.png">

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ☁️ Server

- [x] Update `server/index.js` to handle POST requests to /api/auth/sign-in
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client

- [x] Update component to handle log in and store passwords using JSON web token

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
