### ISSUE TITLE
Feature 2: User can view details of an activity

### ISSUE THREAD

**Issue by rosemary-liang** [rosemary-liu/toddletots#2]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can view details and description of an activity.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User can click any activity preview to view the details of an individual activity. User can go back to home page by clicking the back icon.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![View Selected Activity](https://user-images.githubusercontent.com/95596680/162846918-13d03544-3740-4b43-a15f-351fcedc3bf2.png)

![View Selected Activity (1)](https://user-images.githubusercontent.com/95596680/162846926-51932093-f65d-4a7e-ac01-3b76081e30e4.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ⚡ Client

- [x] Set up hash routing for individual activities
- [x] Set up app.get for route to activityId and confirm state updates correctly for ActivityDetails component
- [x] Create a component for Activity View to display all information for the activity
- [x] Add bookmark and edit icons
- [x] Add get directions button

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
