### ISSUE TITLE
Feature 3: User can add a new activity

### ISSUE THREAD

**Issue by rosemary-liang** [rosemary-liu/toddletots#3]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.
![image](https://user-images.githubusercontent.com/95596680/163915251-b64d9a4f-4d23-4fd0-9bac-315473b3b8e2.png)
<img width="955" alt="image" src="https://user-images.githubusercontent.com/95596680/164294580-602884bd-bc08-4c24-9b51-18ca08c9d32b.png">
<img width="758" alt="image" src="https://user-images.githubusercontent.com/95596680/164294671-95404a02-1f8c-44c7-837a-1392036e8c88.png">

<img width="887" alt="image" src="https://user-images.githubusercontent.com/95596680/164282747-8fbc771b-9688-4a75-bca8-54abac9d843e.png">
<img width="887" alt="image" src="https://user-images.githubusercontent.com/95596680/164294002-ca00ab3e-d5a8-4869-b096-d67ed17183d3.png">
<img width="891" alt="image" src="https://user-images.githubusercontent.com/95596680/164294020-ad415634-1a87-439e-81a7-ba3cc275a7e0.png">

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ☁️ Server

- [x] Update `server/index.js` to handle PUT request
   - [x] Parameters should be used from submitted form
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client

- [x] Create hamburger menu and add functionality for Home and Add New Activity links
- [x] Create a component to handle the entry form
   - [x] Create view placeholder for Map view, add an anchor with hash routing to input address manually
   - [x] Create form
      - [x] Use text area for description. The input should save each paragraph with line breaks.
      - [x] Form should show preview of images or inform user if no images uploaded
      - [x] "Submit" button & input validation
         - [x] All fields are required 
         - [x] Set state with all fields
         - [x] If user null, assign userId of 1 for PUT request
   - [x] Edit Images page
      - [x] Use textarea box. The input should save each URL as a separate string, delimited by spaces or a new line.
      - [x] "Upload" button should set state with images and populate preview images on main form view
      - [x] If "Edit Images" button is clicked after images are uploaded, it should be prepopulated with URL's and image previews

- [x] Upon submit, show Success page to confirm that entry was successfully added
   - [x] Check if success will render without a refresh
- [x] Fix form inputs to add back "required" (removed during testing to pre-fill out state)

### 🧑‍⚕️ Clean Up

- [x] Confirm hash routing works as expected
- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
