### ISSUE TITLE
Feature 4: User can edit an activity

### ISSUE THREAD

**Issue by rosemary-liang** [rosemary-liu/toddletots#4]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="458" alt="image" src="https://user-images.githubusercontent.com/95596680/164571021-dddf3aef-cf83-46f5-b5c9-0c56544ca788.png">
<img width="901" alt="image" src="https://user-images.githubusercontent.com/95596680/164571023-4c07cc56-112e-4d83-991c-e7888a9be188.png">

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ☁️ Server

- [x] Update `server/index.js` for the PUT request
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client

- [x] Create Edit Entry component (can we just use NewEntryForm and change title & placeholders?)
   - [x] on componentDidMount, do fetch request to GET existing data using current Id
   - [x] Create form similar to NewEntryForm and pre-populate with existing data
   - [x] Upon submit, do PUT request
   - [x] Upon PUT request success, show Success page

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [ ] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
