### ISSUE TITLE
Feature 5: User can delete an activity

### ISSUE THREAD

**Issue by rosemary-liang** [rosemary-liu/toddletots#5]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

Users will be able to delete an activity and its associated images.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

When the user is on the Edit Entry page, a user can choose to delete an entry by clicking the trash can button in the top right corner, which will open a modal confirming whether the user wants to delete. Clicking "no" closes the modal and returns to Edit Entry page. Clicking "yes" will delete the entry. Upon successful deletion, user will see a confirmation page and have the option to click a button to return to all activities.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/95596680/165558566-996ce2b4-627b-4fc8-96a4-b284db6a58a4.png)
<img width="1409" alt="image" src="https://user-images.githubusercontent.com/95596680/165558576-4789cef2-6b70-4ff5-a9b4-0866ffb5ea53.png">
<img width="636" alt="image" src="https://user-images.githubusercontent.com/95596680/165558590-59c40cab-a4d6-4941-b7d3-a97b79386a5a.png">

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ☁️ Server

- [x] Update `server/index.js` to remove an activity from the activity table
- [x] Update `server/index.js` to remove an images with activityId from images table
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client

- [x] Update EditEntry component to
   - [x] Have trash can icon on top right
   - [x] When button is clicked, modal pops up to ask if entry should be deleted
   - [x] Style the "yes" and "no" buttons
   - [x] If "No" is clicked, do nothing & close modal
   - [x] If "Yes" is clicked, perform fetch request to database and upon response, return to Home

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
