### ISSUE TITLE
Feature 6: User can view map view of activities

### ISSUE THREAD

**Issue by rosemary-liang** [rosemary-liu/toddletots#6]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can view activities on a map within distance range from current location or zip code

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

On the home page, user can click the map icon to open map view of activities that are nearby. It will default to the search results or current coordinates, which ever user was last using on the Home page list view. User can return to list view by clicking list icon.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/95596680/165667610-e9bb7c59-8d5a-4b12-be98-f30b8c1def85.png)
![image](https://user-images.githubusercontent.com/95596680/165667647-6e5ddfdc-53f2-4475-bcfa-87bf8e7e8f83.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ⚡ Client

- [x] Create a component to render Google Maps of current location 

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
