### ISSUE TITLE
Feature 7: User can use location pin to add an activity

### ISSUE THREAD

**Issue by rosemary-liang** [rosemary-liu/toddletots#7]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can drop a pin to add a new activity.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

After user clicks "Add new activity" from hamburger menu, the user will be redirected to a rendered map automatically centered using the current location coordinates. The user can click on a map to drop a pin, and the pin's address information will be passed to the New Entry Form.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/95596680/166302990-e7a586b4-0656-4a9a-ac40-65d1052040e4.png)
![image](https://user-images.githubusercontent.com/95596680/166302995-513ffac7-8f00-442b-8f74-6797e422663b.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ⚡ Client

- [x] Update NewEntryMap component to render a map and pan to current location
- [x] If hash routing is #new-entry-map, render map using SetMarker
   - [x] On each click, the new marker replaces the old marker
   - [x] Send lat/lng of the marker to the New Entry form

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
