### ISSUE TITLE
Feature 9: User can view bookmarked activities in list view

### ISSUE THREAD

**Issue by rosemary-liang** [rosemary-liu/toddletots#9]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User will be able to view a list view of all bookmarks. 

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Users can navigate to a list view of bookmarks using the hamburger menu.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="1145" alt="image" src="https://user-images.githubusercontent.com/95596680/166859344-01444016-f6ae-4545-a99c-459d7bb0c738.png">
<img width="398" alt="image" src="https://user-images.githubusercontent.com/95596680/166859346-3c379795-a2fd-4898-bafe-3edaff634c80.png">
<img width="887" alt="image" src="https://user-images.githubusercontent.com/95596680/166859351-fcafb412-0729-4eff-8b56-da7df26703e5.png">

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ☁️ Server

- [x] Update `server/index.js` to do a fetch request of all activities related to userId and bookmarks.
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client

- [x] Adapt Home component to display list of bookmarked activities

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
